module Constants
  GRYLLUS_BIMACULATUS = 1
  ACHETA_DOMESTICA = 2
  BLAPTICA_DUBIA = 3
  TURKISH_ROACH = 4
  WORM = 5
  PINK_MOUSE = 6
  FUZZY_MOUSE = 7
  HOPPER_MOUSE = 8
  ADULT_MOUSE = 9
  RETIRE_MOUSE = 10
  PINK_RAT = 11
  FUZZY_RAT = 12
  HOPPER_RAT = 13
  ADULT_RAT = 14
  RETIRE_RAT = 15
  ARTIFICIAL_FOOD = 16
  VEGETABLE = 17
  FLUITS = 18
  CHICK = 19
end
